server:
  servlet:
    port: 8080
    context-path: /api

  spring:

    application:
      name: proman-api


  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345678

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
          database-platform: org.hibernate.dialect.PostgreSQL9Dialect

#spring:
 # jpa:
  #  show-sql: true
   # hibernate:
    #  ddl-auto: update

  #spring:
   # autoconfigure:
    #  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #profiles:
   # active: proman
